stages:
  - Build

"Build, Test, Package and Push":
  stage: Build
  tags:
    - redpoint-games-windows
  script: |
    $Timestamp = ([DateTime]::UtcNow)
    $PackageVersion = "$($Timestamp.Year).$(($Timestamp.Day * 12) + $Timestamp.Month).$(($Timestamp.Hour * 60) + $Timestamp.Minute)"
    dotnet build -c Release /p:PackageVersion=$PackageVersion UET/UET.sln
    if ($LastExitCode -ne 0) {
      Write-Host "dotnet build (UET.sln) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
    dotnet msbuild -restore -t:PublishAllRids -p:Configuration=Release -p:BaseUetVersion=$PackageVersion -p:PackageVersion=$PackageVersion UET/uet/uet.csproj
    if ($LastExitCode -ne 0) {
      Write-Host "PublishAllRids (uet.csproj) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
    dotnet test --no-build --logger:"console" --logger:"junit;LogFilePath=$((Get-Location).Path)\TestResults\{assembly}.test-result.xml" -c Release /p:PackageVersion=$PackageVersion UET/UET.sln
    if ($LastExitCode -ne 0) {
      Write-Host "dotnet test (UET.sln) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
    dotnet publish --no-build -c Release /p:PackageVersion=$PackageVersion UET/UET.sln
    if ($LastExitCode -ne 0) {
      Write-Host "dotnet publish (UET.sln) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
    dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key $env:NUGET_API_KEY (Get-ChildItem -Recurse -Filter "*.$PackageVersion.nupkg" | % { $_.FullName })
    if ($LastExitCode -ne 0) {
      Write-Host "dotnet push failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
    $env:B2_ACCOUNT_INFO = Join-Path -Path (Resolve-Path -Path ".") -ChildPath ".b2.db"
    try {
      b2 authorize-account "$env:DL_BACKBLAZE_B2_KEY_ID" "$env:DL_BACKBLAZE_B2_APPLICATION_KEY"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
      b2 upload-file dl-redpoint-games "UET/uet/bin/Release/net7.0/osx.11.0-arm64/publish/uet" "uet/$PackageVersion/macos/uet"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
      b2 upload-file dl-redpoint-games "UET/uet/bin/Release/net7.0/win-x64/publish/uet.exe" "uet/$PackageVersion/windows/uet.exe"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
      Set-Content -Value $PackageVersion -Path latest.txt
      b2 upload-file dl-redpoint-games "latest.txt" "uet/latest"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
    } finally {
      if (Test-Path $env:B2_ACCOUNT_INFO) {
        Write-Output "Cleaning up B2 authentication file..."
        Remove-Item -Force -Path $env:B2_ACCOUNT_INFO
      }
    }
    exit 0
  artifacts:
    reports:
      junit: TestResults/*.test-result.xml
    paths:
      - UET/uet/bin/Release/net7.0/osx.11.0-arm64/publish/uet
      - UET/uet/bin/Release/net7.0/win-x64/publish/uet.exe