stages:
  - Timestamp
  - Build OpenGE Shim
  - Build Pass 1
  - Build Libraries
  - Build Pass 2
  - Publish
  - End

"Timestamp":
  stage: Timestamp
  tags:
    - redpoint-games-windows
  interruptible: true
  script: |
    $Timestamp = ([DateTime]::UtcNow)
    $PackageVersion = "$($Timestamp.Year).$(($Timestamp.Day * 12) + $Timestamp.Month).$(($Timestamp.Hour * 60) + $Timestamp.Minute)"
    Set-Content -NoNewline -Path "package.version" -Value "$PackageVersion"
  artifacts:
    paths:
      - package.version

"Build OpenGE Shim":
  stage: Build OpenGE Shim
  tags:
    - redpoint-games-windows
  needs:
    - Timestamp
  interruptible: true
  script: |
    $PackageVersion = (Get-Content -Raw -Path "package.version").Trim()
    dotnet msbuild -restore -t:Publish -p:RuntimeIdentifier=win-x64 -p:Configuration=Release -p:BaseUetVersion=$PackageVersion -p:PackageVersion=$PackageVersion "-p:OutDir=$((Get-Location).Path)\UET\Redpoint.OpenGE.ProcessExecution\shim-bin\Release\net7.0\win-x64" "-p:PublishDir=$((Get-Location).Path)\UET\Redpoint.OpenGE.ProcessExecution\shim-bin\Release\net7.0\win-x64\publish" UET/Redpoint.OpenGE.Shim/Redpoint.OpenGE.Shim.csproj
    if ($LastExitCode -ne 0) {
      Write-Host "Publish win-x64 (Redpoint.OpenGE.Shim.csproj) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
  artifacts:
    paths:
      - "UET/Redpoint.OpenGE.ProcessExecution/shim-bin/Release/net7.0/win-x64/publish"

"Build Win Pass 1":
  stage: Build Pass 1
  tags:
    - redpoint-games-windows
  needs:
    - Timestamp
    - "Build OpenGE Shim"
  interruptible: true
  script: |
    $PackageVersion = (Get-Content -Raw -Path "package.version").Trim()
    dotnet msbuild -restore -t:Publish -p:RuntimeIdentifier=win-x64 -p:Configuration=Release -p:BaseUetVersion=$PackageVersion -p:PackageVersion=$PackageVersion -p:OpenGEShimIsAlreadyBuilt=true UET/uet/uet.csproj
    if ($LastExitCode -ne 0) {
      Write-Host "Publish win-x64 (uet.csproj) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
  artifacts:
    paths:
      - "UET/uet/bin/Release/net7.0/win-x64/publish/uet.exe"

"Build Mac Pass 1":
  stage: Build Pass 1
  tags:
    - redpoint-games-mac
  needs:
    - Timestamp
    - "Build OpenGE Shim"
  interruptible: true
  script: |
    PACKAGE_VERSION=$(cat package.version | tr -d '\n')
    echo "Package version: $PACKAGE_VERSION"
    dotnet msbuild -restore -t:Publish -p:RuntimeIdentifier=osx.11.0-arm64 -p:Configuration=Release -p:BaseUetVersion=$PACKAGE_VERSION -p:PackageVersion=$PACKAGE_VERSION -p:OpenGEShimIsAlreadyBuilt=true UET/uet/uet.csproj
    # Ensure the thing we built will actually run...
    ./UET/uet/bin/Release/net7.0/osx.11.0-arm64/publish/uet --help
  artifacts:
    paths:
      - "UET/uet/bin/Release/net7.0/osx.11.0-arm64/publish/uet"

"Build, Test and Package Libraries":
  stage: Build Libraries
  tags:
    - redpoint-games-windows
  needs:
    - Timestamp
    - "Build OpenGE Shim"
  interruptible: true
  script: |
    $PackageVersion = (Get-Content -Raw -Path "package.version").Trim()
    dotnet build -c Release /p:PackageVersion=$PackageVersion /p:OpenGEShimIsAlreadyBuilt=true UET/UET.sln
    if ($LastExitCode -ne 0) {
      Write-Host "dotnet build (UET.sln) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
    dotnet test --no-build --logger:"console" --logger:"junit;LogFilePath=$((Get-Location).Path)\TestResults\{assembly}.test-result.xml" -c Release /p:PackageVersion=$PackageVersion UET/UET.sln
    if ($LastExitCode -ne 0) {
      Write-Host "dotnet test (UET.sln) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
    $PackageVersion = (Get-Content -Raw -Path "package.version").Trim()
    dotnet publish --no-build -c Release /p:PackageVersion=$PackageVersion /p:OpenGEShimIsAlreadyBuilt=true UET/UET.sln
    if ($LastExitCode -ne 0) {
      Write-Host "dotnet publish (UET.sln) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
  artifacts:
    reports:
      junit: TestResults/*.test-result.xml
    paths:
      - "**/*.nupkg"

"Build Win Pass 2":
  stage: Build Pass 2
  tags:
    - redpoint-games-windows
  needs:
    - Timestamp
    - "Build OpenGE Shim"
    - "Build Win Pass 1"
    - "Build Mac Pass 1"
    - job: "Build, Test and Package Libraries"
      artifacts: false
  interruptible: true
  script: |
    $PackageVersion = (Get-Content -Raw -Path "package.version").Trim()
    dotnet msbuild -restore -t:Publish -p:RuntimeIdentifier=win-x64 -p:Configuration=Release -p:EmbeddingCrossPlatform=true -p:BaseUetVersion=$PackageVersion -p:PackageVersion=$PackageVersion -p:OpenGEShimIsAlreadyBuilt=true UET/uet/uet.csproj
    if ($LastExitCode -ne 0) {
      Write-Host "Publish win-x64 (uet.csproj) failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
  artifacts:
    paths:
      - "UET/uet/bin/Release/net7.0/win-x64/publish/uet.exe"

"Build Mac Pass 2":
  stage: Build Pass 2
  tags:
    - redpoint-games-mac
  needs:
    - Timestamp
    - "Build OpenGE Shim"
    - "Build Win Pass 1"
    - "Build Mac Pass 1"
    - job: "Build, Test and Package Libraries"
      artifacts: false
  interruptible: true
  script: |
    PACKAGE_VERSION=$(cat package.version | tr -d '\n')
    echo "Package version: $PACKAGE_VERSION"
    dotnet msbuild -restore -t:Publish -p:RuntimeIdentifier=osx.11.0-arm64 -p:Configuration=Release -p:EmbeddingCrossPlatform=true -p:BaseUetVersion=$PACKAGE_VERSION -p:PackageVersion=$PACKAGE_VERSION -p:OpenGEShimIsAlreadyBuilt=true UET/uet/uet.csproj
    # Ensure the thing we built will actually run...
    ./UET/uet/bin/Release/net7.0/osx.11.0-arm64/publish/uet --help
  artifacts:
    paths:
      - "UET/uet/bin/Release/net7.0/osx.11.0-arm64/publish/uet"

"Publish Libraries":
  stage: Publish
  tags:
    - redpoint-games-windows
  needs:
    - Timestamp
    - "Build, Test and Package Libraries"
  interruptible: true
  script: |
    $PackageVersion = (Get-Content -Raw -Path "package.version").Trim()
    dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key $env:NUGET_API_KEY (Get-ChildItem -Recurse -Filter "*.$PackageVersion.nupkg" | % { $_.FullName })
    if ($LastExitCode -ne 0) {
      Write-Host "dotnet push failed with exit code $LastExitCode"
      exit $LastExitCode 
    }
  artifacts:
    paths:
      - "**/*.nupkg"

"Publish Win":
  stage: Publish
  tags:
    - redpoint-games-windows
  needs:
    - Timestamp
    - "Build Win Pass 2"
  interruptible: true
  script: |
    $PackageVersion = (Get-Content -Raw -Path "package.version").Trim()
    $env:B2_ACCOUNT_INFO = Join-Path -Path (Resolve-Path -Path ".") -ChildPath ".b2.db"
    try {
      b2 authorize-account "$env:DL_BACKBLAZE_B2_KEY_ID" "$env:DL_BACKBLAZE_B2_APPLICATION_KEY"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
      b2 upload-file dl-public-redpoint-games "UET/uet/bin/Release/net7.0/win-x64/publish/uet.exe" "uet/$PackageVersion/windows/uet.exe"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
    } finally {
      if (Test-Path $env:B2_ACCOUNT_INFO) {
        Write-Output "Cleaning up B2 authentication file..."
        Remove-Item -Force -Path $env:B2_ACCOUNT_INFO
      }
    }

"Publish Mac":
  stage: Publish
  tags:
    - redpoint-games-windows
  needs:
    - Timestamp
    - "Build Mac Pass 2"
  interruptible: true
  script: |
    $PackageVersion = (Get-Content -Raw -Path "package.version").Trim()
    $env:B2_ACCOUNT_INFO = Join-Path -Path (Resolve-Path -Path ".") -ChildPath ".b2.db"
    try {
      b2 authorize-account "$env:DL_BACKBLAZE_B2_KEY_ID" "$env:DL_BACKBLAZE_B2_APPLICATION_KEY"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
      b2 upload-file dl-public-redpoint-games "UET/uet/bin/Release/net7.0/osx.11.0-arm64/publish/uet" "uet/$PackageVersion/macos/uet"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
    } finally {
      if (Test-Path $env:B2_ACCOUNT_INFO) {
        Write-Output "Cleaning up B2 authentication file..."
        Remove-Item -Force -Path $env:B2_ACCOUNT_INFO
      }
    }

"Publish Timestamp":
  stage: Publish
  tags:
    - redpoint-games-windows
  needs:
    - Timestamp
    - job: "Publish Win"
      artifacts: false
    - job: "Publish Mac"
      artifacts: false
    - job: "Publish Libraries"
      artifacts: false
  interruptible: true
  script: |
    $PackageVersion = (Get-Content -Raw -Path "package.version").Trim()
    $env:B2_ACCOUNT_INFO = Join-Path -Path (Resolve-Path -Path ".") -ChildPath ".b2.db"
    try {
      b2 authorize-account "$env:DL_BACKBLAZE_B2_KEY_ID" "$env:DL_BACKBLAZE_B2_APPLICATION_KEY"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
      Set-Content -Value $PackageVersion -Path latest.txt
      b2 upload-file dl-public-redpoint-games "latest.txt" "uet/latest"
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
    } finally {
      if (Test-Path $env:B2_ACCOUNT_INFO) {
        Write-Output "Cleaning up B2 authentication file..."
        Remove-Item -Force -Path $env:B2_ACCOUNT_INFO
      }
    }

"End":
  stage: End
  tags:
    - redpoint-games-windows
  needs:
    - job: "Publish Win"
    - job: "Publish Mac"
    - job: "Publish Timestamp"
      artifacts: false
  interruptible: true
  script: |
    Write-Host "Build complete."
  artifacts:
    paths:
      - UET/uet/bin/Release/net7.0/osx.11.0-arm64/publish/uet
      - UET/uet/bin/Release/net7.0/win-x64/publish/uet.exe