stages:
  - Timestamp
  - Platform Specific
  - Build Pass 1
  - Build Libraries
  - Build Pass 2
  - Publish
  - End

variables:
  DEVELOPER_DIR: /Users/Shared/UET/SDKs/Mac-14.1/Xcode.app
  FRAMEWORK_TARGET: net8.0
  UET_BUILDING_ON_BUILD_SERVER: "true"
  MSBUILDDISABLENODEREUSE: "1"
  UET_DOTNET_WIN_DL: https://download.visualstudio.microsoft.com/download/pr/6902745c-34bd-4d66-8e84-d5b61a17dfb7/e61732b00f7e144e162d7e6914291f16/dotnet-sdk-8.0.101-win-x64.zip
  UET_DOTNET_MAC_DL: https://download.visualstudio.microsoft.com/download/pr/ef083c06-7aee-4a4f-b18b-50c9a8990753/e206864e7910e81bbd9cb7e674ff1b4c/dotnet-sdk-8.0.101-osx-arm64.tar.gz
  UET_DOTNET_LINUX_DL: https://download.visualstudio.microsoft.com/download/pr/9454f7dc-b98e-4a64-a96d-4eb08c7b6e66/da76f9c6bc4276332b587b771243ae34/dotnet-sdk-8.0.101-linux-x64.tar.gz
  UET_DOTNET_WIN_PATH: ./.dotnet-$FRAMEWORK_TARGET/dotnet/dotnet.exe
  UET_DOTNET_MAC_PATH: ./.dotnet-$FRAMEWORK_TARGET/dotnet/dotnet
  UET_DOTNET_LINUX_PATH: ./.dotnet-$FRAMEWORK_TARGET/dotnet/dotnet
  GIT_CLEAN_FLAGS: -ffdx -e .dotnet-$FRAMEWORK_TARGET/

.shared-windows-net:
  tags:
    - redpoint-games-windows
  before_script:
    - |
      $UET_DOTNET_DIR = ((Get-Location).Path)
      if (!(Test-Path $UET_DOTNET_DIR\.dotnet-${env:FRAMEWORK_TARGET}\dotnet\dotnet-extracted)) {
        if (Test-Path "$UET_DOTNET_DIR\.dotnet-${env:FRAMEWORK_TARGET}") {
          Remove-Item -Recurse -Force "$UET_DOTNET_DIR\.dotnet-${env:FRAMEWORK_TARGET}"
        }
        Write-Host "Setting up .NET SDK..."
        New-Item -ItemType Directory "$UET_DOTNET_DIR\.dotnet-${env:FRAMEWORK_TARGET}" | Out-Null
        curl.exe -L -o "$UET_DOTNET_DIR\.dotnet-${env:FRAMEWORK_TARGET}\dotnet.zip" "${env:UET_DOTNET_WIN_DL}"
        if ($LastExitCode -ne 0) {
          exit $LastExitCode
        }
        Expand-Archive -Path "$UET_DOTNET_DIR\.dotnet-${env:FRAMEWORK_TARGET}\dotnet.zip" -DestinationPath "$UET_DOTNET_DIR\.dotnet-${env:FRAMEWORK_TARGET}\dotnet" -Force | Out-Null
        Set-Content -Path $UET_DOTNET_DIR\.dotnet-${env:FRAMEWORK_TARGET}\dotnet\dotnet-extracted -Value "done"
      }
      $env:PATH = "$UET_DOTNET_DIR\.dotnet-${env:FRAMEWORK_TARGET}\dotnet;${env:PATH}"

.shared-mac-net:
  tags:
    - redpoint-games-mac
  before_script:
    - |
      UET_DOTNET_DIR=$(pwd)
      if [ ! -e "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet/dotnet-extracted" ]; then
        if [ -e "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet" ]; then
          rm -Rf "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet"
        fi
        mkdir -p "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet"
        curl -L -o "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet.tgz" "$UET_DOTNET_MAC_DL"
        pushd "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet"
        tar -xf ../dotnet.tgz || true
        popd
        echo "done" > "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet/dotnet-extracted"
      fi
      export PATH="$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet:$PATH"

.shared-linux-net:
  before_script:
    - |
      UET_DOTNET_DIR=$(pwd)
      if [ ! -e "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet/dotnet-extracted" ]; then
        if [ -e "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet" ]; then
          rm -Rf "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet"
        fi
        mkdir -p "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet"
        curl -L -o "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet.tgz" "$UET_DOTNET_LINUX_DL"
        pushd "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet"
        tar -xf ../dotnet.tgz || true
        popd
        echo "done" > "$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet/dotnet-extracted"
      fi
      export PATH="$UET_DOTNET_DIR/.dotnet-$FRAMEWORK_TARGET/dotnet:$PATH"

include:
  - Build/.platform-maclogging.gitlab-ci.yml
  - Build/.platform-autodiscovery.gitlab-ci.yml
  - Build/.uefs-client.gitlab-ci.yml
  - Build/.uefs-daemon.gitlab-ci.yml
  - Build/.uet-lib.gitlab-ci.yml
  - Build/.uet-pass-1.gitlab-ci.yml
  - Build/.uet-pass-2.gitlab-ci.yml
  - Build/.uet-shim.gitlab-ci.yml
  - Build/.publish-nuget.gitlab-ci.yml
  - Build/.publish-github.gitlab-ci.yml
  - Build/.publish-container-uefs.gitlab-ci.yml
  - Build/.stringenum.gitlab-ci.yml
  
"Timestamp":
  stage: Timestamp
  tags:
    - redpoint-games-windows
  interruptible: true
  script: |
    $Timestamp = ([DateTime]::UtcNow)
    $PackageVersion = "$($Timestamp.Year).$($Timestamp.DayOfYear + 1000).$(($Timestamp.Hour * 60) + $Timestamp.Minute)"
    Set-Content -NoNewline -Path "package.version" -Value "$PackageVersion"
  artifacts:
    paths:
      - package.version